### ISSUE TITLE
Terraform Error: rpc error: code = Unavailable desc = transport is closing

### ISSUE THREAD

**Issue by maartendq** [OpenNebula/addon-terraform#9] opened 2019-10-10 11:50 UTC
Hi,

When trying to apply a plan (simple group creation), I get the following error:

*opennebula_group.group_up: Creating...
Error: rpc error: code = Unavailable desc = transport is closing
panic: runtime error: index out of range*

Error appears to be in this part:
*2019/10/10 13:34:10 [TRACE] EvalWriteState: removing state object for opennebula_group.group_up
2019/10/10 13:34:10 [TRACE] <root>: eval: *terraform.EvalIf
2019/10/10 13:34:10 [TRACE] <root>: eval: *terraform.EvalIf
2019/10/10 13:34:10 [TRACE] <root>: eval: *terraform.EvalWriteDiff
2019/10/10 13:34:10 [TRACE] <root>: eval: *terraform.EvalApplyPost
2019/10/10 13:34:10 [ERROR] <root>: eval: *terraform.EvalApplyPost, err: rpc error: code = Unavailable desc = transport is closing
2019/10/10 13:34:10 [ERROR] <root>: eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing*

After that terraform crashes. The group is created in opennebula though.
Terraform version used is  0.12.10

Br,
Maarten

**Comment by jaypif** [comment] 2019-10-10 12:28
Hi @maartendq 

Can you provide the terraform file or at least the full structure of `resource_opennebula_group` ?

Because I don't reproduce your behavior on the last version of the provider.

regards

**Comment by jaypif** [comment] 2019-10-10 12:42
OK I found the issue
This is because quotas are not set.

the fix is here: https://github.com/OpenNebula/addon-terraform/pull/11

**Comment by maartendq** [comment] 2019-10-10 13:15
Great, I didn't have quota's indeed. Thanks!

**Comment by jaypif** [comment] 2019-10-10 13:44
The PR Has been merged

**Closed by jaypif** 2019-10-10 13:44 UTC
